---
- name: "Add additional packages"
  package: name="{{ item }}" state=latest
  with_items:
    - gcc

- copy:
    src: download_dependencies.sh
    dest: /installs/
    mode: 0755

- shell: /installs/download_dependencies.sh
