---
- name: "Add additional packages"
  package: name="{{ item }}" state=latest
  with_items:
    - gcc

- name: "build golang web service"
  shell: /installs/code_samples/golang/build.sh

- name: "build java web service"
  shell:
    cmd: "/installs/code_samples/pageview_svc/gradlew build"
    chdir: /installs/code_samples/pageview_svc
