---
#- yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
#  when: ansible_distribution == "CentOS"
#
- name: Add postgres repo key
  ansible.builtin.apt_key:
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    state: present

- name: Add postgres repo
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main
    state: present

# Debian specific
- name: Update Repository cache
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Install postgres
  register: pgsql_install
  package: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6

- name: Add postgres utilities to path
  lineinfile:
    dest: /etc/profile.d/postgresql.sh
    line: "export PATH=${PATH}:{{ pgsql_bin_path }}"
    create: yes   

- name: Create database
  command: "{{ pgsql_bin_path }}/initdb"
  args:
    creates: "{{ pgsql_data_path }}/PG_VERSION"

- name: Add listen address
  lineinfile:
    dest: "{{ pgsql_cfg_path }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertbefore: "listen_addresses = 'localhost'"
  notify: Restart postgres

- name: Add Valid Networks
  lineinfile:
    dest: "{{ pgsql_cfg_path }}/pg_hba.conf"
    line: "host     all     all     {{ item }}      md5"
    insertbefore: EOF
  with_items:
    - "172.30.0.0/24"
    - "172.30.1.0/24"
    - "172.16.1.0/26"
    - "172.16.1.64/27"
    - "172.16.1.96/27"
  notify: Restart postgres

- name: Fix HBA
  replace:
    path: "{{ pgsql_cfg_path }}/pg_hba.conf"
    regexp: '(^local.*|^host.*)(peer$|ident$)'
    replace: '\1trust'
  notify: Restart postgres

- name: "Flush handlers"
  meta: flush_handlers
  #- name: Restart postgres
  #  service:
  #    name: "postgresql@9.6-{{pgsql_cluster_name}}"
  #    state: restarted
  #    enabled: yes
  #  when: hba_changed is defined and hba_changed.changed

- name: Create Users
  script: create_users.sh

- name: Load Objects
  shell: "psql -U pageview < /installs/code_samples/pgsql/content.sql"

- name: Create basic content
  script: create_content.sh
