---
#- yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
#  when: ansible_distribution == "CentOS"
#
- name: Add postgres repo key
  ansible.builtin.apt_key:
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    state: present

- name: Add postgres repo
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main
    state: present

- name: Install postgres
  register: pgsql_install
  package: name={{ item }} state=present
  with_items:
    - postgresql-9.6
    - postgresql-contrib-9.6

- name: Add postgres utilities to path
  lineinfile:
    dest: /etc/profile.d/postgresql.sh
    line: "export PATH=${PATH}:{{ pgsql_bin_path }}"
    create: yes   

- name: Create database
  command: "{{ pgsql_bin_path }}/initdb"
  args:
    creates: "{{ pgsql_data_path }}/postgresql.conf"

- name: Add listen address
  lineinfile:
    dest: "{{ pgsql_data_path }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertbefore: "listen_addresses = 'localhost'"

- name: Fix HBA
  replace:
    path: "{{ pgsql_data_path }}/pg_hba.conf"
    regexp: '(^local.*|^host.*)(peer$|ident$)'
    replace: '\1trust'

- name: Add Valid Networks
  lineinfile:
    dest: "{{ pgsql_data_path }}/pg_hba.conf"
    line: "host     all     all     {{ item }}      md5"
    insertbefore: EOF
  with_items:
    - "172.30.0.0/24"
    - "172.30.1.0/24"
    - "172.16.1.0/26"
    - "172.16.1.64/27"
    - "172.16.1.96/27"

- name: Start postgres
  service: name=postgresql-9.6 state=started enabled=yes

- name: Create Users
  script: create_users.sh

- name: Load Objects
  shell: "psql -U tgburrin < /installs/code_samples/pgsql/content.sql"

- name: Create basic content
  script: create_content.sh
