---
- copy:
    src: "{{ item }}"
    dest: "/etc/default/{{ item }}"
  with_items:
    - kafka.sh
    - zookeeper.sh

- unarchive:
    src: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_version_full }}.tgz"
    dest: /opt
    remote_src: yes
    validate_certs: no
    creates: "/opt/kafka_{{ kafka_version_full }}"

- name: "Linking {{ kafka_version_full }} to 'kafka'"
  ansible.builtin.file:
    src: "/opt/kafka_{{ kafka_version_full }}"
    dest: "/opt/kafka"
    state: link

- lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^[#]?delete.topic.enable=true"
    line: "delete.topic.enable=true"

- lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^log.retention.hours"
    line: "log.retention.hours=24"

- lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^[#]?listeners=PLAINTEXT://:9092"
    line: "listeners=PLAINTEXT://:9092"

- lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^[#]?advertised.listeners="
    line: "advertised.listeners=PLAINTEXT://{{ ansible_fqdn }}:9092"

- lineinfile:
    path: "/opt/kafka/bin/zookeeper-server-start.sh"
    insertafter: "^base_dir"
    firstmatch: yes
    line: "test -f /etc/default/zookeeper.sh && . /etc/default/zookeeper.sh"

- lineinfile:
    path: "/opt/kafka/bin/kafka-server-start.sh"
    insertafter: "^base_dir"
    firstmatch: yes
    line: "test -f /etc/default/karka.sh && . /etc/default/karka.sh"

- name: Copy systemd unit files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - zookeeper.service
    - kafka.service

      #- wait_for:
      #    port: 2181
      #    delay: 10
      #    state: started

- name: Enable zookeeper
  service:
    name: zookeeper
    state: started
    enabled: yes

- name: Enable kafka
  service:
    name: kafka
    state: started
    enabled: yes

- shell: ./kafka-topics.sh --create --topic messages --if-not-exists --partitions 1 --replication-factor 1 --bootstrap-server localhost:9092
  args:
    chdir: "/opt/kafka/bin"
