---
- setup:
#- debug: var=hostvars

- name: Collecting ec2 instance facts
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "us-east-1"
  register: ec2_instances

#- debug: var=ec2_instances

- name: Building hostlist
  set_fact:
          ec2hostlist: "{{ ec2hostlist|default([]) + [ { 'address': item.private_ip_address|default(''), 'name': item.tags.Name, 'internal_name': item.private_dns_name|default('') } ] }}"
  with_items: "{{ ec2_instances.instances }}"
  when: item.tags.automated == "true" and item.private_ip_address is defined

#- debug:
#    msg: >-
#            {{ item }}
#  with_items: "{{ ec2hostlist }}"

- name: "Add to hosts (AWS)"
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ item.address }} {{ item.internal_name }} {{ item.name }} {{ item.internal_name.split('.')[0] }}"
  with_items: "{{ ec2hostlist }}"

- name: "Add standard packages"
  package: name="{{ item }}" state=latest
  with_items:
    - git
    - bind9-utils # bind-utils for centos
    - sysstat
    - gpg

#- file: path=/installs/code_samples state=absent

- name: "Get git repository"
  file: path=/installs state=directory
- git: repo=https://github.com/tgburrin/code_samples.git dest=/installs/code_samples update=no version=master
- copy:
    dest: "/root/.ssh/id_rsa"
    content: "{{ tgb_internal_key }}"
    owner: root
    group: root
    mode: 0600
- copy:
    dest: "/root/.ssh/"
    src: "{{ item.name }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
      - { name: id_rsa.pub, mode: "0644" }
      - { name: config, mode: "0644" }
      - { name: authorized_keys, mode: "0644" }
- lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin "
    line: "PermitRootLogin yes"
  register: sshd_config
- service:
    name: sshd
    state: restarted
  when: sshd_config.changed
