---
- lineinfile:
    path: /etc/ld.so.conf.d/local.conf
    line: "/usr/local/lib"
    create: yes

- package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - gcc-c++
    - cmake
    - make

- file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /installs/librdkafka
    - /installs/cJSON

- unarchive: src=https://github.com/open-source-parsers/jsoncpp/archive/1.7.3.tar.gz dest=/installs remote_src=yes creates=/installs/jsoncpp-1.7.3

- git: repo="{{ item.repo }}" dest="{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/edenhill/librdkafka.git", dest: "/installs/librdkafka" }
    - { repo: "https://github.com/DaveGamble/cJSON.git", dest: "/installs/cJSON" }

- shell: ./configure && make -j"{{ ansible_processor_cores }}" && make install
  args:
    chdir: /installs/librdkafka
    creates: "/usr/local/lib/librdkafka.so"

- shell: cmake . && make -j"{{ ansible_processor_cores }}" && make install
  args:
    chdir: /installs/cJSON
    creates: "/usr/local/lib/libcjson.so"

- shell: cmake -DBUILD_SHARED_LIBS=ON . && make -j"{{ ansible_processor_cores }}" && make install
  args:
    chdir: /installs/jsoncpp-1.7.3
    creates: "/usr/local/lib/libjsoncpp.so"

- command: ldconfig -v

# This is heavily tied to the version of postgres
- lineinfile:
    path: /etc/profile.d/pkgconfig.sh
    line: "export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/pgsql-9.6/lib/pkgconfig"
    create: yes
    owner: root
    group: root
    mode: 0755

- shell: bash --login -c make
  args:
    chdir: /installs/code_samples/c

- shell: bash --login -c make
  args:
    chdir: /installs/code_samples/cpp/Default
