---
- package:
    name: cmake
    state: latest

- git: repo="{{ item.repo }}" dest="{{ item.dest }}"
  with_items:
    - { repo: https://github.com/edenhill/librdkafka.git, dest: /installs/librdkafka }
    - { repo: https://github.com/DaveGamble/cJSON.git, dest: /installs/cJSON }
