---
#yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present

- name: Add postgres repo key
  ansible.builtin.apt_key:
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
    state: present

- name: Add postgres repo
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main
    state: present

- name: Install postgres
  register: pgsql_install
  package: name={{ item }} state=present
  with_items:
    - postgresql96-devel
    - postgresql96-contrib

- name: Add postgres utilities to path
  lineinfile:
    dest: /etc/profile.d/postgresql.sh
    line: "export PATH=${PATH}:{{ pgsql_bin_path }}"
    create: yes   

