---
- unarchive:
    src: "http://www-us.apache.org/dist/kafka/0.11.0.0/kafka_2.12-0.11.0.0.tgz"
    dest: /opt
    remote_src: yes
    validate_certs: no
    creates: "/opt/kafka_2.12-0.11.0.0"

- lineinfile:
    path: "/opt/kafka_2.12-0.11.0.0/config/server.properties"
    regexp: "^#delete.topic.enable=true"
    line: "delete.topic.enable=true"

- lineinfile:
    path: "/opt/kafka_2.12-0.11.0.0/config/server.properties"
    regexp: "^log.retention.hours"
    line: "log.retention.hours=24"

- lineinfile:
    path: "/opt/kafka_2.12-0.11.0.0/config/server.properties"
    regexp: "^#listeners=PLAINTEXT://:9092"
    line: "listeners=PLAINTEXT://:9092"

- lineinfile:
    path: "/opt/kafka_2.12-0.11.0.0/config/server.properties"
    regexp: "^#advertised.listeners="
    line: "advertised.listeners=PLAINTEXT://kafka01.ec2.internal:9092"

- command: /opt/kafka_2.12-0.11.0.0/bin/zookeeper-server-start.sh -daemon /opt/kafka_2.12-0.11.0.0/config/zookeeper.properties

- wait_for:
    port: 2181
    delay: 10
    state: started

- command: /opt/kafka_2.12-0.11.0.0/bin/kafka-server-start.sh -daemon /opt/kafka_2.12-0.11.0.0/config/server.properties

- shell: ./kafka-topics.sh --zookeeper localhost --create --topic messsages --partitions 1 --replication-factor 1
  args:
    chdir: /opt/kafka_2.12-0.11.0.0/bin
