---
- name: Reload postgres
  service:
    name: "postgresql@{{ pgsql_version }}-{{pgsql_cluster_name}}"
    state: reloaded
    enabled: yes

- name: Restart postgres
  service:
    name: "postgresql@{{ pgsql_version }}-{{pgsql_cluster_name}}"
    state: restarted
    enabled: yes
