---
#- debug: var=build_hosts
#- debug: var=inst

- name: Provision a set of instances
  ec2_instance:
     aws_access_key: "{{ aws_access_key }}"
     aws_secret_key: "{{ aws_secret_key }}"
     image_id: "{{ ami_id }}"
     instance_initiated_shutdown_behavior: "terminate"
     instance_type: "{{ inst.instance_type if inst.instance_type is defined else instance_type }}"
     key_name: "{{ aws_key_name }}"
     name: "{{ item }}"
     network:
        assign_public_ip: false
        delete_on_termination: true
     region: "us-east-1"
     security_group: "default"
     tags:
        instance_type: "{{ inst.type }}"
        cloud_provider: "aws"
        automated: "true"
     termination_protection: false
     vpc_subnet_id: "subnet-e389cbb9"
     wait: true
  register: ec2
  with_sequence: start=1 end={{ inst.num }} format="{{ inst.name }}%02d"

#- debug: var=ec2.results

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.instances[0].private_ip_address }}"
    port: 22
    delay: 5
    timeout: 320
    state: started
  with_items: "{{ ec2.results }}"

