---
- hosts: localhost
  tasks:
    - name: Collecting ec2 instance facts
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "us-east-1"
      register: ec2_instances
    - name: Building hostlist
      set_fact:
              ec2hostlist: "{{ ec2hostlist|default([]) + [ { 'address': item.private_ip_address, 'name': item.tags.Name } ] }}"
      with_items: "{{ ec2_instances.instances }}"
      when: item.tags.automated == "true"
    - file: path=/tmp/ec2hosts.ns state=absent
    - lineinfile: dest=/tmp/ec2hosts.ns state=present create=True backup=no line="server 172.16.1.5"
    - lineinfile: dest=/tmp/ec2hosts.ns backup=no line="update delete {{ item.name }}.ec2.tgburrin.net. A"
      with_items: "{{ ec2hostlist }}"
    - lineinfile: dest=/tmp/ec2hosts.ns backup=no insertafter=EOF line="send"
    - shell: "nsupdate < /tmp/ec2hosts.ns"
    - name: Terminate instances that were previously launched
      ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "us-east-1"
        state: 'absent'
        instance_ids:
          - "{{ item.instance_id }}"
      with_items: "{{ ec2_instances.instances }}"
      when: item.tags.automated == "true"
