---
- hosts: localhost
  tasks:
    - name: Building hostlist
      set_fact:
        hostlist: "{{ hostlist|default([]) + [ { 'address': item, 'name': hostvars[item].ec2_tag_Name } ] }}"
      with_items: "{{ groups['tag_automated_true'] }}"
    - file: path=/tmp/ec2hosts.ns state=absent
    - lineinfile: dest=/tmp/ec2hosts.ns state=present create=True backup=no line="server 172.16.1.1"
    - lineinfile: dest=/tmp/ec2hosts.ns backup=no line="update delete {{ item.name }}.ec2.tgburrin.net. A"
      with_items: "{{ hostlist }}"
    - lineinfile: dest=/tmp/ec2hosts.ns backup=no insertafter=EOF line="send"
    - shell: "nsupdate < /tmp/ec2hosts.ns"

- hosts: tag_automated_true
  tasks:
    - name: "Creating a shutting down automated instances"
      shell: poweroff
      become: true
      become_user: root
