---
- hosts: us-east-1
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/tgburrin_aws

  tasks:
    - name: "Creating a shutting down automated instances"
      shell: poweroff
      become: true
      become_user: root
