---
- hosts: localhost
  tasks:
    - name: Collecting ec2 instance facts
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "us-east-1"
      register: ec2_instances
    - name: Building hostlist
      set_fact:
              ec2hostlist: "{{ ec2hostlist|default([]) + [ { 'address': item.private_ip_address|default(''), 'name': item.tags.Name|default('') } ] }}"
      with_items: "{{ ec2_instances.instances }}"
      when: item.tags.automated == "true"

    - name: Printing out collected info
      ansible.builtin.debug:
        msg: "{{ ec2hostlist|default([]) }}"
    - debug: var=ec2_instances.instances
